ALTER TABLE orders MODIFY total_amount DOUBLE NOT NULL;
ALTER TABLE orders MODIFY order_status VARCHAR(64) DEFAULT NULL;
ALTER TABLE orders MODIFY tracking_number VARCHAR(64) DEFAULT NULL;
ALTER TABLE orders MODIFY modified_at TIMESTAMP DEFAULT NULL DEFAULT CURRENT_TIMESTAMP;