
CREATE TABLE item (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    desc VARCHAR (2048) NOT NULL ,
    size VARCHAR(64) NOT NULL,
    color VARCHAR(64) NOT NULL,
    price FLOAT NOT NULL DEFAULT 0,
    discount FLOAT NOT NULL DEFAULT 0,
    SKU VARCHAR (128) NOT NULL,
    quantity_stock INT NOT NULL DEFAULT 0,
    image_path VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
