
CREATE TABLE  orders (
    id INT NOT NULL AUTO_INCREMENT,
    client_id INT NOT NULL,
    amount FLOAT NOT NULL DEFAULT 0,
    first_name VARCHAR(128) NOT NULL,
    last_name VARCHAR(128) NOT NULL,
    address VARCHAR(2048) NOT NULL,
    city VARCHAR(32) NOT NULL,
    zip_code VARCHAR(64) NOT NULL,
    country VARCHAR(32) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    email VARCHAR(64) NOT NULL,
    ordered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shipped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tracking_number VARCHAR(64) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE ON UPDATE CASCADE
);