
CREATE TABLE payment (
    id INT NOT NULL AUTO_INCREMENT,
    client_id INT NOT NULL,
    order_id INT NOT NULL,
    amount FLOAT NOT NULL,
    payment_status VARCHAR(64) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE ON UPDATE CASCADE
);

