
CREATE TABLE payment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    amount FLOAT NOT NULL,
    currency VARCHAR(32) NOT NULL,
    stripe_id VARCHAR(256) NOT NULL,
    payment_status VARCHAR(64) NOT NULL,
    provider VARCHAR (64) NOT NULL,
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE ON UPDATE CASCADE
);